### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by brunocalado** [Javiondox/html-to-scene#2]
Hi, Great module!

There is something wrong with the update for this module. It always require to update, but it never finish.

![image](https://user-images.githubusercontent.com/4999783/149677147-934ed39f-acec-4108-b1d7-862d817fb7b4.png)
![image](https://user-images.githubusercontent.com/4999783/149677158-891c6aa5-dc1e-4d94-9aa6-e940e4aec332.png)

**Comment by Javiondox** [comment]
I might have messed up the module.json. Check if you can update right now, in the worst case scenario, you can uninstall and reinstall the module (without entering the world in the progress) and you won't lose any data associated.

I need to look for a tool chain that automates the progress, because this issue is occurring too much to my liking. (And it is made by human mistake, as it isn't automated)

**Comment by brunocalado** [comment]
same
![image](https://user-images.githubusercontent.com/4999783/150596877-bf292e83-48bd-463b-8436-ca035ba466ad.png)

**Comment by Javiondox** [comment]
Finally I have gotten around to fixing it. The module was reporting the wrong version when it was actually updated. Sorry for the delay, life happened. You can update to fix the version number once for all. (It won't add any new feature, just fix the number and make it stop updating, you are already in the 1.0.12). If the issue persists, open a new one please.
